version: '3.2'

services:
  db:
    image: mysql:5.7
    env_file:
      - ./environments/dev.txt
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
    image: app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./environments/dev.txt
    ports:
      - 5000:5000
    volumes:
      - .:/opt/app:delegated

volumes:
  mysql-data:
